module.exports = {
  DASHBOARD_READ: 'dashboard.read',
  MACHINES_READ: 'machines.read',
  MACHINES_WRITE: 'machines.write',
  MACHINES_UPDATE_OWN: 'machines.update_own',
  REPORTS_READ: 'reports.read',
  REPORTS_EXPORT: 'reports.export',
  USERS_MANAGE: 'users.manage',
  ROLES_MANAGE: 'roles.manage',
  AUDIT_READ: 'audit.read',
  PRODUCTION_READ: 'production.read',
  PRODUCTION_MANAGE: 'production.manage',
  WORK_ORDERS_EXECUTE: 'work_orders.execute',
  SHIFTS_MANAGE: 'shifts.manage',
  PARTS_READ: 'parts.read',
  PARTS_MANAGE: 'parts.manage',
};
